version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    - path: .  # install project itself so that the version can be retrieved with importlib.metadata.version

sphinx:
  configuration: docs/source/conf.py
